# -*- coding: utf-8 -*-
"""ICP2_700745532.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJuFTm9wmqf1WHanxTZTzLz3q4wtJHYH
"""

First_name = ( input("Your First Name : "))
last_name = (input("Your Last Name : "))
Full_Name = print(First_name + last_name)

def string_alternative(Str):
    output = ""
    for a in range(len(Str)):
        if a % 2 == 0:
            output += Str[a]
    return output

print(string_alternative("Good evening"))

file1 = open('input.txt', 'r')
counts = dict()
data = file1.read()
words = data.split()
for word in words:
    if word in counts:
        counts[word] += 1
    else:
        counts[word] = 1
print(counts)

f = open('output.txt', 'w')
f.write(data)
f.write('\nword_count:\n')
for key, value in counts.items():
    f.write(f"{key}: {value}\n")
f.close()

L1=list(map(float,input().split()))
L2=[]
for x in L1:
    x=x*2.54
    L2.append(x)
print(L2)

L1=list(map(float,input().split()))
L2=[x*2.54 for x in L1]
print(L2)